### ISSUE TITLE
Can't import ES6 Map

### ISSUE THREAD

**Issue by jasich** [babel/babel-jest#28] opened 2015-06-04 03:03 UTC
I'm trying to define a Map in a module and export it.  In my Jest test I want to import it to use it like, but it comes back undefined.  Other things in the same module get imported without an issue.

friend-test.js
```
jest.dontMock('../');

import { friends, myRealFriends } from '../';

describe('friends',function () {
  it('should import friends', function () {
    expect(friends).toBeDefined();
  });
  it('should import real friends', function () {
    expect(myRealFriends).toBeDefined();
  })
});
```

friend.js
```
const friends = new Map([
  ['jason', 36],
  ['paul', 36]
]);

export {friends as friends};

const otherFriends = ['123', '456'];
export {otherFriends as myRealFriends};
```

and I get 

```
 FAIL  src/__tests__/friend-test.js (0.614s)
● friends › it should import friends
  - Expected undefined to be defined.
       at Spec.<anonymous> (~/babel-jest-test/src/__tests__/friend-test.js:7:23)
```

**Comment by sebmck** [comment] 2015-06-04 03:04
Duplicate of #16, please search next time, thanks!

**Closed by sebmck** 2015-06-04 03:04 UTC

**Comment by jasich** [comment] 2015-06-04 11:26
Thanks and sorry. I didn't get why the Map was undefined, but I'm guessing that it means that Jest was mocking it out as the result of a function call, hence undefined, instead of it being a mocked object.
