### ISSUE TITLE
Non-mocked import: unexpected behavior?

### ISSUE THREAD

**Issue by chcokr** [babel/babel-jest#34] opened 2015-06-26 14:09 UTC
Given the following code:

```JS
// sum.js
function sum(value1, value2) {
  return value1 + value2;
}
module.exports = sum;
```

This test passes:

```JS
jest.dontMock('../sum');
var sum = require('../sum');

describe('sum', function() {
  it('adds 1 + 2 to equal 3', function() {
    expect(sum(1, 2)).toBe(3);
  });
});
```

But this doesn't:

```JS
jest.dontMock('../sum');
import sum from '../sum';

describe('sum', function() {
  it('adds 1 + 2 to equal 3', function() {
    expect(sum(1, 2)).toBe(3);
  });
});
```

Failure message:

```
 FAIL  __tests__/sum-test.js (1.07s)
● sum › it adds 1 + 2 to equal 3
  - Expected: undefined toBe: 3
```

I think it *should* pass?

**Comment by sebmck** [comment] 2015-06-26 14:10
Duplicate of #16.

**Comment by chcokr** [comment] 2015-06-26 14:11
Ah, that was fast. Thanks!

**Closed by sebmck** 2015-06-26 14:10 UTC
